---
title: "Homework1"
output: html_document
---
Read Datasets

```{r}
#Intel Dataset
intel <- read.csv(file="C:/Users/dglownia/Documents/GitHub/CSC-465-Data-Visualization/Homework1/Datasets/Intel-1998.csv",head=TRUE,sep=",")

experiment <- read.csv(file="C:/Users/dglownia/Documents/GitHub/CSC-465-Data-Visualization/Homework1/Datasets/PerceptionExperiment2007-2015Fall.csv",head=TRUE,sep=",")

require(gdata)
infant = read.xls ("C:/Users/dglownia/Documents/GitHub/CSC-465-Data-Visualization/Homework1/Datasets/InfantData.xlsx"), sheet = 1, header = TRUE)

```



Problem 1 (Intel Dataset)

a.

```{r}
library(ggplot2)

ggplot(data=intel, aes(x=Date, y=Close, group=1)) +
  geom_line() +
  geom_point() +
  expand_limits(y=0) +
  xlab("Date") + ylab("Close") +
  ggtitle("Closing Price vs. Date")


```


b.

```{r}
library(ggplot2)

ggplot(data=intel, aes(x=Date, y=Volume)) + 
    geom_bar(colour="black", fill="#DD8888", width=.8, stat="identity") + 
    guides(fill=TRUE) +
    xlab("Time of day") + ylab("Total Volume") +
    ggtitle("Average Volume")

```


c.

```{r}

hist(intel$Volume, 
     main="Histogram for Volume", 
     xlab="Volume", 
     border="blue")

```


d.

```{r}
library(ggplot2)

intel[, "PriceRange"] <- NA
intel$PriceRange <- intel$High - intel$Low

p1 <- ggplot(intel, aes(x = Volume, y = PriceRange)) +
xlab("Volume") + ylab("Price Range") +
    ggtitle("Price Range")
p1 + geom_point()

```


Problem 2 (experiment.xls)

a.

```{r}

experiment[, "Error"] <- NA
experiment$Error <- experiment$Response - experiment$TrueValue

hist(experiment$Error, 
     main="Distribution of Errors", 
     xlab="Errors", 
     border="blue")

```


b.


```{r}

library(ggplot2)

ggplot(data=experiment, aes(x=Trial, y=Error)) + 
    geom_bar(colour="black", fill="#DD8888", width=.8, stat="identity") + 
    xlab("Trail") + ylab("Error") +
    ggtitle("Median Errors by Test")

```


c.

```{r}

experiment[, "stdErrorCategory"] <- NA
experiment$stdErrorCategory <- ifelse(experiment$Error > 0.5,"A", "NAN")
experiment$stdErrorCategory <- ifelse(experiment$Error < -0.5,"C", "NAN")
experiment$stdErrorCategory <- ifelse(experiment$Error >= -0.5 || experiment$Error <= 0.5 ,"B", "NAN")

ggplot(data=experiment, aes(x=Trial, y=stdErrorCategory)) + 
    geom_bar(colour="black", fill="#DD8888", width=.8, stat="identity") + 
    xlab("Trail") + ylab("Error") +
    ggtitle("Median Errors by Test")


```


d.

```{r}

experiment[, "absError"] <- NA
experiment$absError <- abs(experiment$Error)

ggplot(data=experiment, aes(x=Trial, y=absError)) + 
    geom_bar(colour="black", fill="#DD8888", width=.8, stat="identity") + 
    xlab("Trail") + ylab("Error") +
    ggtitle("Median Errors by Test")

```


e. 

Conclusion:
```{r}

```



Problem 3

a.

```{r}

```


b.

```{r}

```


c.

```{r}

```


Problem 4 

a. 

```{r}

```


b.

```{r}

```


Problem 5

a.

```{r}

```


b.

```{r}

```


c.

```{r}

```

